{% set name = "mct_quantizers" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sony/mct_quantizers/archive/v{{ version }}.tar.gz
  sha256: ea6ab1f271187484d53cb515577b2d0cb59332058ebca5878474e6524ab1d4ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy <2
    - packaging

test:
  imports:
    - mct_quantizers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sony/mct_quantizers
  license: Apache-2.0
  license_file: LICENSE.md
  summary: |
    "MCT Quantizers facilitates the easy quantization of neural networks in Keras and PyTorch, 
    equipped with a robust set of pre-defined quantizers and the flexibility to implement custom quantizers."

extra:
  recipe-maintainers:
    - Chizkiyahu
