{% set name = "mct_quantizers" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sony/mct_quantizers/archive/v{{ version }}.tar.gz
  sha256: 0b1e13ba3a02362b644db88fc75f0215d23f79fbfd30ca260315a46425d1c948

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2
    - packaging

test:
  imports:
    - mct_quantizers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sony/mct_quantizers
  license: Apache-2.0
  license_file: LICENSE.md
  summary: |
    "MCT Quantizers facilitates the easy quantization of neural networks in Keras and PyTorch, 
    equipped with a robust set of pre-defined quantizers and the flexibility to implement custom quantizers."

extra:
  recipe-maintainers:
    - Chizkiyahu
